// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSQGf8dmLXf54VoaxZL5n_u9fkdo-OAfo',
    appId: '1:661070387995:web:4c6ac6e9408c133c6551be',
    messagingSenderId: '661070387995',
    projectId: 'teste-flutter-b329c',
    authDomain: 'teste-flutter-b329c.firebaseapp.com',
    storageBucket: 'teste-flutter-b329c.appspot.com',
    measurementId: 'G-63V35XQWB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpC1wm6tWToxMz59gNQD7ap5mi9-84VHY',
    appId: '1:661070387995:android:0069bdb0afe06cda6551be',
    messagingSenderId: '661070387995',
    projectId: 'teste-flutter-b329c',
    storageBucket: 'teste-flutter-b329c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzb0N96--WK0HoBUvnsf0Q2cos3xx0Tc',
    appId: '1:661070387995:ios:16b2205d042568576551be',
    messagingSenderId: '661070387995',
    projectId: 'teste-flutter-b329c',
    storageBucket: 'teste-flutter-b329c.appspot.com',
    iosBundleId: 'com.example.testeFlutter',
  );

}